CREATE TABLE IF NOT EXISTS words (
  id SERIAL PRIMARY KEY,
  word VARCHAR(100) NOT NULL UNIQUE,
  meaning TEXT NOT NULL,
  example TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



INSERT INTO words (word, meaning, example)
VALUES
('aberration', 'A departure from what is normal, usual, or expected.', 'The sudden snowstorm in July was a total aberration.'),
('alacrity', 'Brisk and cheerful readiness.', 'She accepted the invitation with alacrity.'),
('anomaly', 'Something that deviates from what is standard or expected.', 'There are a number of anomalies in the present system.'),
('arcane', 'Understood by few; mysterious or secret.', 'The professor''s lecture was filled with arcane references to medieval alchemy.'),
('assiduous', 'Showing great care and perseverance.', 'The project succeeded thanks to her assiduous attention to detail.'),
('austere', 'Severe or strict in manner, attitude, or appearance.', 'The monks lived an austere life in the mountains.'),
('bellicose', 'Demonstrating aggression and willingness to fight.', 'The politician''s bellicose rhetoric fueled the tension between the nations.'),
('benevolent', 'Well-meaning and kindly.', 'The benevolent stranger donated a large sum to the orphanage.'),
('cacophony', 'A harsh, discordant mixture of sounds.', 'A cacophony of car horns filled the city streets during rush hour.'),
('capricious', 'Given to sudden and unaccountable changes of mood or behavior.', 'The capricious weather made planning the picnic impossible.'),
('catharsis', 'The process of releasing strong or repressed emotions.', 'Writing in her journal provided a much-needed catharsis.'),
('chicanery', 'The use of trickery to achieve a political, financial, or legal purpose.', 'He wasn''t above using a little chicanery to win the contract.'),
('cogent', 'Clear, logical, and convincing.', 'The lawyer presented a cogent argument that swayed the jury.'),
('conundrum', 'A confusing and difficult problem or question.', 'The lack of evidence presents a difficult conundrum for the investigators.'),
('copious', 'Abundant in supply or quantity.', 'She took copious notes during the three-hour lecture.'),
('curtail', 'To reduce in extent or quantity; impose a restriction on.', 'We must curtail our spending if we want to save for a house.'),
('dearth', 'A scarcity or lack of something.', 'There is a dearth of qualified candidates for the position.'),
('deferential', 'Showing respect and humble submission.', 'He spoke in a deferential tone to his elders.'),
('deleterious', 'Causing harm or damage.', 'The chemical spill had a deleterious effect on the local ecosystem.'),
('demagogue', 'A political leader who seeks support by appealing to popular desires rather than using rational argument.', 'The crowd was easily swayed by the demagogue''s fiery speech.'),
('didactic', 'Intended to teach, particularly in having moral instruction as an ulterior motive.', 'The children''s book was entertaining without being overly didactic.'),
('diffident', 'Modest or shy because of a lack of self-confidence.', 'The diffident boy sat quietly at the back of the classroom.'),
('disparate', 'Essentially different in kind; not allowing comparison.', 'The two cultures are quite disparate, despite their geographic proximity.'),
('dissemble', 'To conceal one''s true motives, feelings, or beliefs.', 'She smiled, dissembling her true frustration with the situation.'),
('ebullient', 'Cheerful and full of energy.', 'The team was in an ebullient mood after winning the championship.'),
('eclectic', 'Deriving ideas, style, or taste from a broad and diverse range of sources.', 'Her music collection is eclectic, ranging from jazz to heavy metal.'),
('efficacy', 'The ability to produce a desired or intended result.', 'The new drug has shown great efficacy in treating the virus.'),
('egregious', 'Outstandingly bad; shocking.', 'The report contained several egregious errors.'),
('eloquent', 'Fluent or persuasive in speaking or writing.', 'His eloquent speech moved the audience to tears.'),
('elusive', 'Difficult to find, catch, or achieve.', 'Success remained elusive for the struggling artist.'),
('enervate', 'To cause someone to feel drained of energy or vitality.', 'The intense heat enervated the hikers by midday.'),
('engender', 'To cause or give rise to a feeling, situation, or condition.', 'The new policy helped to engender a sense of trust among the staff.'),
('enigma', 'A person or thing that is mysterious, puzzling, or difficult to understand.', 'The disappearance of the plane remains an enigma to this day.'),
('ephemeral', 'Lasting for a very short time.', 'Fame is often ephemeral, fading as quickly as it arrives.'),
('equanimity', 'Mental calmness, composure, and evenness of temper.', 'She accepted both criticism and praise with equanimity.'),
('erudite', 'Having or showing great knowledge or learning.', 'The erudite scholar could speak five languages fluently.'),
('esoteric', 'Intended for or likely to be understood by only a small number of people.', 'The debate was over an esoteric point of tax law.'),
('euphemism', 'A mild or indirect word substituted for one considered too harsh.', '‘Passed away’ is a common euphemism for ‘died’.'),
('exacerbate', 'To make a problem, bad situation, or negative feeling worse.', 'The humidity will only exacerbate your breathing problems.'),
('facetious', 'Treating serious issues with deliberately inappropriate humor.', 'Stop being facetious; this is a serious conversation.'),
('fastidious', 'Very attentive to and concerned about accuracy and detail.', 'He is fastidious about keeping his workspace organized.'),
('fortuitous', 'Happening by accident or chance rather than design.', 'Their meeting was entirely fortuitous, as neither had planned to be there.'),
('garrulous', 'Excessively talkative, especially on trivial matters.', 'The garrulous neighbor kept me at the door for an hour.'),
('gregarious', 'Fond of company; sociable.', 'She was a gregarious child who made friends wherever she went.'),
('hackneyed', 'Lacking significance through having been overused; unoriginal.', 'The plot of the movie was filled with hackneyed clichés.'),
('harangue', 'A lengthy and aggressive speech.', 'He delivered a long harangue against the government''s policies.'),
('iconoclast', 'A person who attacks cherished beliefs or institutions.', 'The young artist was hailed as an iconoclast for his radical style.'),
('idiosyncrasy', 'A mode of behavior or way of thought peculiar to an individual.', 'One of his idiosyncrasies is that he always wears mismatched socks.'),
('impecunious', 'Having little or no money.', 'The impecunious student lived on ramen noodles for a month.'),
('impetuous', 'Acting or done quickly and without thought or care.', 'His impetuous decision to quit his job surprised everyone.'),
('incisive', 'Intelligently analytical and clear-thinking.', 'The critic gave an incisive analysis of the new novel.'),
('indolent', 'Wanting to avoid activity or exertion; lazy.', 'They spent an indolent afternoon lounging by the pool.'),
('ineffable', 'Too great or extreme to be expressed or described in words.', 'The beauty of the sunset was ineffable.'),
('innocuous', 'Not harmful or offensive.', 'It was an innocuous remark, but she took great offense to it.'),
('insipid', 'Lacking flavor or vigor; boring.', 'The conversation was insipid and failed to hold my interest.'),
('intransigent', 'Unwilling or refusing to change one''s views or to agree about something.', 'The parties remained intransigent, and the negotiations failed.'),
('intrepid', 'Fearless; adventurous.', 'The intrepid explorer ventured deep into the uncharted jungle.'),
('laconic', 'Using very few words.', 'His laconic reply of ''No'' ended the discussion.'),
('lethargic', 'Affected by lethargy; sluggish and apathetic.', 'The heavy meal made me feel lethargic for the rest of the day.'),
('loquacious', 'Tending to talk a great deal; talkative.', 'The loquacious host kept the party guests entertained all night.'),
('lucid', 'Expressed clearly; easy to understand.', 'The teacher gave a lucid explanation of a complex theory.'),
('magnanimous', 'Generous or forgiving, especially toward a rival.', 'He was magnanimous in defeat, shaking hands with the winner.'),
('malleable', 'Easily influenced; pliable.', 'The minds of young children are very malleable.'),
('mellifluous', 'Sweet or musical; pleasant to hear.', 'The singer’s mellifluous voice filled the concert hall.'),
('mendacious', 'Not telling the truth; lying.', 'The politician''s mendacious statements were quickly debunked.'),
('mercurial', 'Subject to sudden or unpredictable changes of mood.', 'His mercurial temperament made him difficult to work with.'),
('mitigate', 'Make less severe, serious, or painful.', 'Drainage systems were built to mitigate the effects of flooding.'),
('mollify', 'Appease the anger or anxiety of someone.', 'He tried to mollify his boss by offering a sincere apology.'),
('myriad', 'A countless or extremely great number.', 'There are myriad possibilities for what the future might hold.'),
('nefarious', 'Wicked or criminal.', 'The villain hatched a nefarious plot to take over the city.'),
('obdurate', 'Stubbornly refusing to change one''s opinion or course of action.', 'Despite the evidence, he remained obdurate in his belief.'),
('obsequious', 'Obedient or attentive to an excessive degree.', 'The waiter was obsequious, constantly hovering over our table.'),
('ostentatious', 'Characterized by vulgar or pretentious display.', 'The billionaire’s ostentatious mansion was visible from miles away.'),
('paradigm', 'A typical example or pattern of something; a model.', 'The discovery led to a paradigm shift in the field of physics.'),
('paucity', 'The presence of something only in small or insufficient quantities.', 'There is a paucity of evidence to support his claims.'),
('pedantic', 'Excessively concerned with minor details or rules.', 'He can be rather pedantic when it comes to grammar.'),
('perfunctory', 'Carried out with a minimum of effort or reflection.', 'He gave the room a perfunctory glance before leaving.'),
('pernicious', 'Having a harmful effect, especially in a gradual or subtle way.', 'The pernicious influence of the cult destroyed many families.'),
('petulant', 'Childishly sulky or bad-tempered.', 'The petulant child threw a tantrum when he didn''t get his way.'),
('placate', 'Make someone less angry or hostile.', 'The manager tried to placate the angry customer with a refund.'),
('pragmatic', 'Dealing with things sensibly and realistically.', 'We need to take a pragmatic approach to solving this budget crisis.'),
('precarious', 'Not securely held or in position; dangerously likely to fall or collapse.', 'The ladder was in a precarious position against the wall.'),
('proclivity', 'A tendency to choose or do something regularly.', 'He has a proclivity for getting into trouble.'),
('profligate', 'Recklessly extravagant or wasteful in the use of resources.', 'The profligate prince spent his entire inheritance in a year.'),
('pundit', 'An expert in a particular subject who is frequently called on to give opinions.', 'The political pundit was invited to debate on the news.'),
('quixotic', 'Exceedingly idealistic; unrealistic and impractical.', 'His quixotic quest to end world hunger was admired but seen as impossible.'),
('recalcitrant', 'Having an obstinately uncooperative attitude toward authority.', 'The recalcitrant student refused to follow any of the school rules.'),
('reticent', 'Not revealing one''s thoughts or feelings readily.', 'She was reticent about her past, rarely mentioning her family.'),
('salient', 'Most noticeable or important.', 'What are the salient points of the new proposal?'),
('sanguine', 'Optimistic or positive, especially in an apparently bad situation.', 'He is sanguine about the company''s chances of success.'),
('scrupulous', 'Diligent, thorough, and extremely attentive to details.', 'The research was carried out with scrupulous attention to accuracy.'),
('serendipity', 'The occurrence of events by chance in a happy or beneficial way.', 'By pure serendipity, I found the book I was looking for in a thrift store.'),
('spurious', 'Not being what it purports to be; false or fake.', 'The claims made in the advertisement were proven to be spurious.'),
('superfluous', 'Unnecessary, especially through being more than enough.', 'The extra decorations were superfluous and made the room feel cluttered.'),
('surreptitious', 'Kept secret, especially because it would not be approved of.', 'He took a surreptitious peek at the answers during the test.'),
('tenuous', 'Very weak or slight.', 'The link between the two crimes is tenuous at best.'),
('ubiquitous', 'Present, appearing, or found everywhere.', 'Cell phones have become ubiquitous in modern society.'),
('venerable', 'Accorded a great deal of respect, especially because of age or wisdom.', 'The venerable professor was retired after fifty years of teaching.'),
('veracity', 'Conformity to facts; accuracy; truthfulness.', 'The jury doubted the veracity of the witness''s testimony.'),
('vociferous', 'Vehement or clamorous; outspoken.', 'He was a vociferous critic of the new tax laws.');